sudo: required
services:
  - docker

before_install:
  - docker build -t DhansvW/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true DhansvW/react-test npm test

after_success:
    - docker build -t dhansvw/multi-client ./client
    - docker build -t dhansvw/multi-nginx ./nginx
    - docker build -t dhansvw/multi-server /server
    - docker build -t dhansvw/multi-worker ./worker

    # login to the docker CLI

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    # take those images and push them to dockerhub

    - docker push dhansvw/multi-client
    - docker push dhansvw/multi-nginx
    - docker push dhansvw/multi-server
    - docker push dhansvw/multi-worker

